### ISSUE TITLE
How to switch position of year and months on header?

### ISSUE THREAD

**Issue by bubgdgnanh** [mengxiong10/vue2-datepicker#223]
I have some use cases when I need to switch postion of year and months on header, and I need to add suffix for year.

I you can please let me know how to do it. Thanks!

**Comment by mengxiong10** [comment]
v2.7.0
use css to do it.  Adjust the value of margin by yourself

```css
.mx-calendar-panel-date .mx-current-month {
  float: right;
  margin-right: 25px;
}

.mx-calendar-panel-date .mx-current-year {
  float: left;
  margin-left: 25px;
}

.mx-calendar-panel-date .mx-current-year::after {
  content: '年'
}

```
