### ISSUE TITLE
Can you customize the location of shortcuts, such as on the left side of the date

### ISSUE THREAD

**Issue by ZY1014** [mengxiong10/vue2-datepicker#254]

**Comment by mengxiong10** [comment]
You change it by css.
```css
.mx-shortcuts-wrapper {
    position: absolute;
    left: 0;
    height: 100%;
    width: 100px;
    box-shadow: rgba(0, 0, 0, 0.1) 1px 0px;
}
.mx-range-wrapper {
  margin-left: 100px;
}

.mx-shortcuts-wrapper .mx-shortcuts:after {
    content: '';
}

```
