### ISSUE TITLE
Disable "Year selection" in datepicker header

### ISSUE THREAD

**Issue by sdzhurova** [mengxiong10/vue2-datepicker#255]
Hi!
Is there a possibility to disable the click on the year in the header?
Also is there a possibility to remove the arrows connected with the year?

![image](https://user-images.githubusercontent.com/15360847/52954428-78668980-338a-11e9-8916-9ed1114d53c1.png)

Thank you :)

**Comment by mengxiong10** [comment]
use css
```css
.mx-current-year {
  pointer-events: none;
}
.mx-icon-last-year, ..mx-icon-next-year {
  display: none
}

```
