### ISSUE TITLE
Feature: Vertical Shortcuts (UI improvements)

### ISSUE THREAD

**Issue by timothymarois** [mengxiong10/vue2-datepicker#302]
Ability to do vertical shortcuts, something like this?

Right now, we're very limited with the shortcuts we can place at the top. And the last shortcut always has the "|" at the end. 

_The current shortcuts:_
![Screenshot 2019-04-30 14 35 20](https://user-images.githubusercontent.com/2489333/56984955-437a6e00-6b55-11e9-99a3-1fe4fb9112b3.png)

**_Proposing Vertical shortcuts:_**
![Screenshot 2019-04-30 14 35 32](https://user-images.githubusercontent.com/2489333/56984934-38bfd900-6b55-11e9-964a-c40df269f14b.png)

**Comment by mengxiong10** [comment]
use the css
```css
      .mx-shortcuts-wrapper {
        float: left;
        width: 80px;
        border-bottom: 0;
      }
      .mx-shortcuts:after {
        display: none;
      }
      .mx-range-wrapper {
        border-left: 1px solid rgba(0, 0, 0, 0.05);
      }

```

**Comment by timothymarois** [comment]
@mengxiong10 Thanks for the quick tip. Almost worked for me, I'm trying to get the calendar to be on the side of it instead of collapsing, any thoughts on how to do to it without rigging a fixed width to the whole thing. 

![Screenshot 2019-05-07 09 50 53](https://user-images.githubusercontent.com/2489333/57304659-bcc21580-70ad-11e9-9d9d-c72ef18896aa.png)

**Comment by mengxiong10** [comment]
https://codesandbox.io/s/wz4j413z8
```css
.mx-datepicker-popup {
  display: flex;
}
.mx-shortcuts-wrapper {
  width: 100px;
  border-bottom: 0;
  border-right: 1px solid rgba(0, 0, 0, 0.05);
}
.mx-shortcuts:after {
  display: none;
}

```
