### ISSUE TITLE
How to highlight certain days?

### ISSUE THREAD

**Issue by zabavnikov** [mengxiong10/vue2-datepicker#342]

**Comment by mengxiong10** [comment]
use the css 
```css
td[title="2019-09-02"] {
  color: green;
}
```
