### ISSUE TITLE
[Feature request]re-select the month select matrix with type = "month"

### ISSUE THREAD

**Issue by FPTSonPM3** [mengxiong10/vue2-datepicker#411]
re-select the month select matrix with type = "month"

With type = "month", vue2-datepicker is currently with matrix as
1 2 3
4 5 6
7 8 9
10 11 12

I want to fix it
1 2 3 4
5 6 7 8
9 10 11 12
Sincere thanks

**Comment by mengxiong10** [comment]
try css
```scss

.mx-table-month {
  tr {
    display: inline;
  }
  td {
    float: left;
    width: 56px; // 224 / 4
    height: 74px; // 224 /3
    line-height: 74px;
  }
}


```

**Comment by FPTSonPM3** [comment]
Thank you very much, I have solved my problem @mengxiong10

**Comment by FPTSonPM3** [comment]
@mengxiong10 I have a problem, as you can see in the picture, in my red section. I want to customize it to hide it, I don't want it to show so much, it's too much, I want it to only show 5 weeks instead of 6 weeks as currently.
![image](https://user-images.githubusercontent.com/40652135/72501907-adb17b00-386a-11ea-9b19-d5c0040fd6b1.png)

**Comment by mengxiong10** [comment]
```css
.mx-date-row:last-child {
  display: none;
}

```
