### ISSUE TITLE
How can I delete the calendar icon?

### ISSUE THREAD

**Issue by Lexzum** [mengxiong10/vue2-datepicker#418]
help me please

**Comment by mengxiong10** [comment]
use css
```css
.mx-icon-calendar {  display: none }

```

or slot
```html
 <date-picker v-model="time3" >
     <i slot="icon-calendar"></i>
</date-picker>

```
