### ISSUE TITLE
Can't change input style

### ISSUE THREAD

**Issue by kevin8656** [mengxiong10/vue2-datepicker#440]
![CleanShot 2020-03-12 at 00 45 48@2x](https://user-images.githubusercontent.com/24646190/76441731-da14ee00-63fa-11ea-991a-10effd762651.jpg)

How can I change the input style ? 

I use scss wrote a class style .mx-input but not working . 

and I use input-class attr change input to another class, but it still can't render my style.

thanks

**Comment by mengxiong10** [comment]
.mx-datepicker .mx-input {
   ///
}

**Comment by kevin8656** [comment]
Can i write those code in  scss file an import  into a  vue file to  change style?
I use it now but it is not working.
in scss file
```css
    .mx-datepicker {
      height: 47px;
      width: 100%;
      border-color: #519fc5;
      &::placeholder {
        border-color: #519fc5;
        color: #519fc5;
      }
      .mx-input {
        height: 47px;
        width: 100%;
        border-color: #519fc5 !important;
      }
    }
```
in vue
```
                <date-picker
                  v-model="form.createdYear"
                  type="year"
                  placeholder="製造年份"
                  valueType="format"
                />
```
