### ISSUE TITLE
Option to style all weekends?

### ISSUE THREAD

**Issue by itdzuj1** [mengxiong10/vue2-datepicker#443]
Is there an option to style all weekends on the calendar?

Thanks!

**Comment by mengxiong10** [comment]
use css.
```css

.mx-date-row .cell:nth-child(1),
.mx-date-row .cell:nth-child(7) {
  color: red;
}
```
