### ISSUE TITLE
hide not-current-month

### ISSUE THREAD

**Issue by itdzuj1** [mengxiong10/vue2-datepicker#445]
Hello! How can i hide not-current-month cell's?

With css i have got this:
http://joxi.ru/L2181VECgOp0Gm
http://joxi.ru/nAyZPRGTjQBwVr

Thanks!

**Comment by mengxiong10** [comment]
```css
.mx-table-date .not-current-month > div {
  display: none;
}

```
