### ISSUE TITLE
Range Calendar Display 

### ISSUE THREAD

**Issue by Be-Like** [mengxiong10/vue2-datepicker#455]
Is there a way to only display one calendar when the date picker type is range?

**Comment by mengxiong10** [comment]
The easiest way is to use css.
```css
.mx-range-wrapper .mx-calendar:last-child {
  display: none;
}

```
