### ISSUE TITLE
[Feature request] Make it possible to set the current day

### ISSUE THREAD

**Issue by nicolashuber** [mengxiong10/vue2-datepicker#496]
**What problem does this feature solve?**
I'm using vue2-datepicker on application that has timezone configuration, so the current date may be different from what the browser provides.

![Screenshot from 2020-07-07 09-11-58 png](https://user-images.githubusercontent.com/7015206/86779735-4662cf80-c032-11ea-9b51-3f72835751c6.png)

The browser local timezone is GTM-0300, but the user settings is GMT+1000, so the day marked on the calendar may be different over the hours.

**What does the proposed API look like?**
There must be some way to define the current date, for example:

```
<date-picker currentDate="new Date(2020, 6, 7)" />
```

**Comment by tsguterres** [comment]
I also need this change.
If you can add this feature I would be very grateful

**Comment by mengxiong10** [comment]
You can add the class by `get-classes`.
```html
<date-picker :get-classes="getClasses" />

```
```js
  methods: {
    getClasses(date) {
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      // set the yersterday is `current-date`
      if (date.getTime() === today.getTime() - 24 * 3600 * 1000) {
        return 'current-date';
      }
      return '';
    },
  },

```

```css
// remove the default style of 'today'
.mx-table-date .today {
  color: inherit !important;
}

.mx-table-date .current-date {
  color: blue;
}

```
