### ISSUE TITLE
[Feature request] calendar icon on left

### ISSUE THREAD

**Issue by geofany** [mengxiong10/vue2-datepicker#532]
**What problem does this feature solve?**
![image](https://user-images.githubusercontent.com/37582643/96412162-ddcfe500-1213-11eb-944f-e0f0bbae68e6.png)

**What does the proposed API look like?**

**Comment by mengxiong10** [comment]
change the css
```css
.mx-input {
  padding: 6px 10px 6px 30px !important;
}
.mx-icon-calendar, .mx-icon-clear {
  left: 8px !important;
}

```
