### ISSUE TITLE
[Feature request] Generic calendar for picking birth day and month

### ISSUE THREAD

**Issue by mchestnut** [mengxiong10/vue2-datepicker#553]
**What problem does this feature solve?**
Using the datepicker to pick a birth day and month (DD/MM) without the year.

Currently we're using this component in several places across our app, so I'd like to continue using it. However, we have a field for setting a birth day and month but we're not storing the year for privacy.

It'd be ideal if the datepicker had an option with no years shown for this. I can imagine the month panel looks the same, but for the day panel, have the days of the week hidden or just always start on Sunday. February would also need to include 29 days for leap years.

**What does the proposed API look like?**
Add a new type to the `type` prop. Perhaps "monthday" or "noyear"?

This may be too niche of a request, but thought I'd throw it out there!

**Comment by mengxiong10** [comment]
I think you can use css to control which dom should be hidden.
```html
<date-picker   popup-class="birthday" format="DD/MM" />
```
```css
.birthday {
  .mx-btn-current-year,
  .mx-btn-icon-double-left,
  .mx-btn-icon-double-right {
    display: none;
  }
}

```
