### ISSUE TITLE
Header modification

### ISSUE THREAD

**Issue by mick340** [mengxiong10/vue2-datepicker#568]
Is it also possible to modify the header?

Current situation i have removed the year switchers:

<img width="252" alt="Screenshot 2021-01-19 at 20 22 07" src="https://user-images.githubusercontent.com/8590308/105082530-04601f00-5a94-11eb-8a59-4618b0e751eb.png">

The situation i would like to get:
<img width="456" alt="Screenshot 2021-01-19 at 20 22 29" src="https://user-images.githubusercontent.com/8590308/105082558-0fb34a80-5a94-11eb-9fab-68401a1baf22.png">

So i want to left align the month + year text. And want the 2 arrows to switch between months on the right.

**Comment by mengxiong10** [comment]
use css

**Comment by mick340** [comment]
> use css

Could you make an example?

**Comment by mengxiong10** [comment]
```css
.mx-btn-icon-left {
  position: absolute;
  right: 40px;
}
.mx-btn-icon-right {
  position: absolute;
  right: 20px;
}

```
