### ISSUE TITLE
[Feature Request] Add width and iconShow props

### ISSUE THREAD

**Issue by RSurya99** [mengxiong10/vue2-datepicker#673]
**What problem does this feature solve?**
By adding width props will make you can customize the width of its parent, because the current width is fixed to 210px and iconShow is for people who don't want to use an icon, so they can disable it.

**Comment by mengxiong10** [comment]
You can change them by `css`.
```css
.mx-datepicker {  width: 300px }
.mx-icon-calendar { display: none }

```
