### ISSUE TITLE
[Feature request] Time selection panel, disable scrolling for AM / PM subpanel

### ISSUE THREAD

**Issue by akhchan99** [mengxiong10/vue2-datepicker#697]
**What problem does this feature solve?**

If the v-model time is in the PM, the AM will be scroll out of viewable area, since there're just 2 items in the list, it doesn't really need the scroll option.

I think this could apply to specified time selection too, if the list is short, scrolling could be disabled?

**What does the proposed API look like?**

**Comment by mengxiong10** [comment]
If you want to disable scroll. You can change the css.
```css
.mx-time-list[data-type="ampm"]::after {
  height: 0 !important;
}

```
