### ISSUE TITLE
is it possible to change position of datepicker icon?

### ISSUE THREAD

**Issue by ruchitaladha** [mengxiong10/vue2-datepicker#702]
I want to change date icon and popup to be left align...how can I do it

**Comment by mengxiong10** [comment]
You  can change the css.
```css
.mx-input {
    padding-left: 30px;
    padding-right: 10px;
}
.mx-icon-calendar {
    left: 8px
}

```
