### ISSUE TITLE
How can I change the overall font size?

### ISSUE THREAD

**Issue by bernardwiesner** [mengxiong10/vue2-datepicker#712]
I am trying to change the overall font size for the calendar and time table. I can change individual css like:

```css
.mx-table-date {
  td,
  th {
    height: 32px;
    font-size: 16px;
  }
}
```

But how can I increase the overall font size? Or must I do it individually for every css selector? Actually I just want to increase the overall size of the calendar.
