### ISSUE TITLE
How can we set the fonts to not be "greyed out" when datepicker is disabled ?

### ISSUE THREAD

**Issue by dgouveris** [mengxiong10/vue2-datepicker#719]

**Comment by mengxiong10** [comment]
change the css
```css
.mx-input:disabled {
     color: '';
     background: ''
}

```
